# Generated by Django 6.0.4 on 2026-05-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={},
        ),
        migrations.AddField(
            model_name='payment',
            name='sender_bank',
            field=models.CharField(blank=True, choices=[('CBE', 'Commercial Bank of Ethiopia'), ('Awash', 'Awash Bank'), ('Dashen', 'Dashen Bank'), ('BOA', 'Bank of Abyssinia'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
